export const siteConfig = {
  name: "MCQs Fun - Create and Play MCQ Quiz Games",
  description:
    "MCQs Fun is a platform where users can create and play multiple-choice quiz games. Learn, test your knowledge, and have fun!",

  keywords: [
    "reactjs",
    "nextjs",
    "react",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "postgresql",
    "sonner",
    "zustand",
    "lucide-react",
    "next-themes",
    "clerk-themes",
    "clerk",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
    "hackathon",
    "summer-hackathon",
    "xata",
    "prisma",
    "innjest",
    "ai",
    "openai",
  ] as Array<string>,
  authors: {
    name: "Nikhil Kumar",
    url: "https://twitter.com/nikhilkr23",
  },
} as const;
